version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: BackendDockerfile
    container_name: plant_disease_backend
    ports:
      - "8000:80"
    volumes:
      - ./app:/app/app
      - ./mini_model.h5:/model/mini_model.h5
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/

  frontend:
    build:
      context: ./plant-disease-frontend
      dockerfile: ../FrontendDockerFile
    container_name: plant_disease_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: plant_disease_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
